export enum API_ROUTES {
  LOGIN = "/doctor/login",
  REGISTER = "/doctor/register",
  CREATE_FOLDER = "/project/create",
  UPDATE_FOLDER = "/project/update",
  DELETE_FOLDER = "project/delete",
  CREATE_STUDY = "/project/study/create",
  UPDATE_STUDY = "/project/study/update",
  DELETE_STUDY = "/project/study/delete",
  UPDATE_STUDY_BLUK_QUESTIONS = "/question/update-bulk-study-question",
  FETCH_TEMPLATES = "/project/condition-based-assessment-template/fetch-dashboard-analytics",
  FETCH_CONDITIONAL_BASED_CATEGORY_TEMPLATES = "/project/condition-based-assessment-template/fetch",
  FETCH_SINGLE_ASSESSMENT_QUESTIONS = "/question/fetch",
  FETCH_FOLDERS_STUDIES = "/project/fetch-dashboard-analytics",
  FETCH_STUDIES_FOLDER_ID = "/project/study/fetch",
  FILTER_PATIENTS = "/patient/patients",
  CREATE_PROTOCOL = "/protocol/create",
  FFETCH_PROTOCOLS = "/protocol/fetch",
  UPDATE_PROTOCOLS = "/protocol/update",
  DELETE_PROTOCOLS = "/protocol/delete",
  FFETCH_SURVEY = "/protocol/survey/fetch",
  CREATE_SURVEY = "/protocol/survey/create",
  UPDATE_SURVEY = "/protocol/survey/update",
  FETCH_QUESTION_TYPES = "/question/get-question-option-types",
  CREATE_SURVEY_QUESTION = "/question/create-survey-question",
  UPDATE_SURVEY_QUESTION = "/question/update-survey-question",
  FETCH_EMOJIS = "/emoji/fetch",
}
